### ISSUE TITLE
story-0 SailPoint Deployment

### ISSUE THREAD

**Issue by DustinYansberg** [DustinYansberg/ProjectThree-BackEnd#1]

**Comment by jaredmai** [comment]
IIQ was containerized by following this guide and heavily modifing it to work with our instance of IIQ. The MySQL Server version was dropped as it is being hosted on a seperate Azure resource, and the IIQ version was updated to 8.3.

https://community.sailpoint.com/t5/IdentityIQ-Wiki/Dockerization-of-IdentityIQ/ta-p/136819
